
package translaterr;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "JSONException", targetNamespace = "http://service.xxl.com/")
public class JSONException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private JSONException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public JSONException_Exception(String message, JSONException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public JSONException_Exception(String message, JSONException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: translaterr.JSONException
     */
    public JSONException getFaultInfo() {
        return faultInfo;
    }

}
