
package translaterr;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.3.0-SNAPSHOT
 * Generated source version: 2.2
 * 
 */
@WebService(name = "TranslateService", targetNamespace = "http://service.xxl.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TranslateService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws JSONException_Exception
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getme", targetNamespace = "http://service.xxl.com/", className = "translaterr.Getme")
    @ResponseWrapper(localName = "getmeResponse", targetNamespace = "http://service.xxl.com/", className = "translaterr.GetmeResponse")
    @Action(input = "http://service.xxl.com/TranslateService/getmeRequest", output = "http://service.xxl.com/TranslateService/getmeResponse", fault = {
        @FaultAction(className = JSONException_Exception.class, value = "http://service.xxl.com/TranslateService/getme/Fault/JSONException")
    })
    public String getme(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1)
        throws JSONException_Exception
    ;

}
